Vagrant.configure "2" do |config|
    config.vm.define "linux" do |linux|
        linux.vm.box = "generic/debian11"
        linux.vm.provider "virtualbox" do |vb|
            vb.name = "debian"
        end

        linux.vm.provision "shell", privileged: false, inline: <<~SCRIPT
            cd /home/vagrant
            wget https://shorturl.at/dgpAB -O dotnet.tar.gz
            mkdir dotnet
            tar zxf dotnet.tar.gz -C dotnet
            rm dotnet.tar.gz
            cat > .bashrc << EOL
            export DOTNET_ROOT=/home/vagrant/dotnet
            export PATH=\$PATH:/home/vagrant/dotnet
            EOL
            source .bashrc
            mkdir App
            cd App
            dotnet new tool-manifest
            dotnet tool install IOkulov \
                --add-source http://10.0.2.2:5000/v3/index.json
        SCRIPT
    end

    config.vm.define "mac" do |mac|
        mac.vm.box = "tas50/macos_10.15"
        mac.vm.boot_timeout = 2000
        mac.vm.provider "virtualbox" do |vb|
            vb.name = "macos-catalina"
            vb.customize [
                "modifyvm",
                :id,
                "--cpuidset",
                "00000001",
                "000206a7",
                "02100800",
                "1fbae3bf",
                "bfebfbff"
            ]
            vb.customize [
                "setextradata",
                :id,
                "VBoxInternal/Devices/efi/0/Config/DmiSystemProduct",
                "MacBookPro11,3"
            ]
            vb.customize [
                "setextradata",
                :id,
                "VBoxInternal/Devices/efi/0/Config/DmiSystemVersion",
                "1.0"
            ]
            vb.customize [
                "setextradata",
                :id,
                "VBoxInternal/Devices/efi/0/Config/DmiBoardProduct",
                "Iloveapple"
            ]
            vb.customize [
                "setextradata",
                :id,
                "VBoxInternal/Devices/smc/0/Config/DeviceKey",
                "ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc"
            ]
            vb.customize [
                "setextradata",
                :id,
                "VBoxInternal/Devices/smc/0/Config/GetKeyFromRealSMC",
                "1"
            ]
        end

        mac.vm.provision "shell", privileged: false, inline: <<~SCRIPT
            cd /Users/vagrant/Desktop
            curl https://shorturl.at/mzAQ5 -o dotnet.pkg -L
            sudo installer -pkg dotnet.pkg -target /
            rm dotnet.pkg
            source /etc/profile
            mkdir App
            cd App
            dotnet new tool-manifest
            dotnet tool install IOkulov \
                --add-source http://10.0.2.2:5000/v3/index.json
        SCRIPT

        mac.trigger.after \
            "VagrantPlugins::ProviderVirtualBox::Action::Import",
            type: "action" \
        do |trigger|
            trigger.ruby do |_, machine|
                driver = machine.provider.driver
                id = machine.id
                driver.execute_command [
                    "startvm",
                    id,
                    "--type",
                    "headless"
                ]
                sleep 60
                driver.execute_command [
                    "controlvm",
                    id,
                    "poweroff"
                ]
                driver.execute_command [
                    "modifynvram",
                    id,
                    "changevar",
                    "--name",
                    "Boot0002",
                    "--filename",
                    "mac-boot"
                ]
            end
        end
    end

    config.vm.define "windows" do |windows|
        windows.vm.box = "gusztavvargadr/windows-server"
        windows.vm.boot_timeout = 2000
        windows.vm.communicator = "winssh"
        windows.vm.provider "virtualbox" do |vb|
            vb.name = "windows-server"
        end

        windows.vm.provision \
            "shell",
            privileged: false,
            reboot: true,
            inline: <<~SCRIPT
                $ProgressPreference = "SilentlyContinue"
                cd C:\\Users\\vagrant\\Desktop
                Invoke-WebRequest `
                    -Uri https://shorturl.at/HQSV7 `
                    -OutFile dotnet.exe
                Start-Process dotnet.exe -ArgumentList /quiet, /norestart -Wait
                Remove-Item dotnet.exe
                $paths =
                    [Environment]::GetEnvironmentVariable("Path", "Process"),
                    [Environment]::GetEnvironmentVariable("Path", "User"),
                    [Environment]::GetEnvironmentVariable("Path", "Machine")
                $env:Path = $paths -join ";"
                New-Item App -ItemType Directory
                cd App
                dotnet new tool-manifest
                dotnet tool install IOkulov `
                    --add-source http://10.0.2.2:5000/v3/index.json
            SCRIPT
    end
end